name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  
  flutter_localizations:
    sdk: flutter

  http: ^1.2.0
  dio: ^5.7.0

  # 감정 분석을 위한 카메라/음성
  camera: ^0.11.3
  record: ^6.1.2
  path_provider: ^2.1.5
  permission_handler: ^11.4.0

  # 차트, UI
  fl_chart: ^0.66.0
  cupertino_icons: ^1.0.8
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.2.2

  # 3D 모델
  model_viewer_plus: ^1.9.3

  # 🔊 말동이 음성 재생용
  audioplayers: ^5.2.0

  speech_to_text: ^7.3.0
  flutter_tts: ^3.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/background/
    - assets/icon/
    - assets/model.glb
