name: flutter_application
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # 아이콘 / 날짜 관련
  cupertino_icons: ^1.0.8
  intl: ^0.19.0

  # ✅ HTTP 통신용 Dio 패키지
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
